### ISSUE TITLE
레이아웃 개발

### ISSUE THREAD

**Issue by kong33** [s-center/kiosk#15]

**Comment by kong33** [comment]
원래는 위의 밴드? 와 밑의 정사각형 선택지를 따로 컴포넌트로 빼려고 했지만 시간도 부족하고 어차피 계속 쓰이니 layout안에 한 번에 구현하겠습니다!

**Comment by ENvironmentSet** [comment]
위의 밴드라고 불러주신 게 아마 네비게이션 바(혹은 Tab라 부르기도 합니다)인 거 같은데 '향 선택' 페이지에서 재사용되는만큼 이 부분은 컴포넌트로 따로 분리하시는 게 좋을 거 같아요. 밑의 정사각형 선택지를 레이아웃 안에서 바로 구현하는 건 괜찮아 보입니다.

**Comment by kong33** [comment]
앗 이 코멘트 보지 못하고 향 선택 페이지일 때와 아닐 때를 prop으로 지정해 하단 탭이 보일지 말지를 결정할 수 있게 코드를 짜 보았는데 확인 해보시고 불편할 것 같으면 알려주세요! + 하단 정사각형 선택지는 생각해보니 각자 생태관리를 하는 게 좋을 것 같아 따로 뺐습니다! 확인 부탁드려용
