### ISSUE TITLE
수정 사항 체크

### ISSUE THREAD

**Issue by kong33** [s-center/kiosk#33]
- [x] 로딩 시간 단축 필요  - 재원님
    - [ ] 캐싱 등 이용
    - [ ] 미리 로드 해두고 발표 

- [x] 다시 한 번 생각해보기 버튼 구현 - 재원님
- [x] 커스텀 디퓨저 저장하기
- [x] 시제품 추천받기
     - [x] recommand 페이지 제작
     - [x] 페이지에서 그림 클릭하면 각 그림에 해당하는 제품 페이지 제작- 재원님
     - [x] 영수증 페이지 제작 -재원님
- [x] #35

- [x] 폰트 한번에 확인
- [x] css 수정
- [x] 바닐라 이미지 (데모이미지) 수정 - keyword
- [x] 4,5,6 페이지 (사용 방법 안내) 구현

- [x] 큐알 코드 생성 대기 페이지
- [x] 큐알코드 페이지

- [x] 시제품 추천받기 버튼 -> recommand 페이지로 연결

**Comment by ENvironmentSet** [comment]
우선순위는 이렇게 되겠네요.

### 1

- keyword 선택 데모 이미지 수정
- 커스텀 디퓨저 저장하기
- 시제품 추천받기
- 제품 추천받기
- 선택 결과 페이지 버튼 위치 조정(중앙정렬이 안 되어있습니다)

### 2

- 이미지 최적화 (일단 압축부터 해봅시다. 압축 -> 미리 로딩 -> CDN -> spriting>
- 선택 취소 기능 구현( 하단 박스 X 위치 수정 및, 버튼 클릭 시 선택 수정 로직 구현)

### 3

- 다시 한 번 생각해보기 버튼 구현
- 사용 방법 안내 구현

**Comment by ENvironmentSet** [comment]
최대한 UI 중심으로 만들어주시면 제가 수요일 새벽 ~ 오후 사이에 기능적인 부분들 구현해보도록 하겠습니다. 

얘네는 제가 맡아보도록 할게요:

- 제품 구매 페이지
- 이미지 최적화
- 다시 한 번 생각해보기 버튼 구현
- 사용 방법 안내 구현

**Comment by kong33** [comment]
네 감사합니다! 그러면 제가 나머지 하나씩 해서 각각 pr 올려두겠습니다 ! 브랜치 따로 안 만들고 저번에 최종으로 만들어진 브랜치에 계속 추가할게요! 
제품 구매 페이지라 함은
<img width="137" alt="image" src="https://github.com/s-center/kiosk/assets/96658105/0a20ade0-c679-464a-9ac1-a6454eda13f0">
요기 말씀하시는 거겠죠?

**Comment by ENvironmentSet** [comment]
NOTE: Try [million.js](https://million.dev/docs/install) for optimization

**Comment by ENvironmentSet** [comment]
> 네 감사합니다! 그러면 제가 나머지 하나씩 해서 각각 pr 올려두겠습니다 ! 브랜치 따로 안 만들고 저번에 최종으로 만들어진 브랜치에 계속 추가할게요!
> 제품 구매 페이지라 함은
> <img alt="image" width="137" src="https://user-images.githubusercontent.com/96658105/280619055-0a20ade0-c679-464a-9ac1-a6454eda13f0.png">
> 요기 말씀하시는 거겠죠?

네네
