### ISSUE TITLE
피그마 4, 5, 6번 페이지 개발

### ISSUE THREAD

**Issue by ENvironmentSet** [s-center/kiosk#6]
사용자가 자신의 취향을 선택할 수 있는 페이지를 개발해야 합니다.

아래와 같은 컴포넌트가 필요할 것으로 예상됩니다.
- 네비게이션 바 (네비게이션 기능이 탑제된)
- 1차원 이미지 슬라이드 (모든 페이지 하단)
- 3D 이미지 슬라이드 (페이지 4)
- 갤러리형 이미지 슬라이드 (페이지 5)
- 캐러셀 (페이지 6)

## 참고자료

<img width="888" alt="image" src="https://github.com/s-center/kiosk/assets/28680594/e4a2aa5a-4f08-4246-9ef2-56d5762ac99c">

- [유튜브 영상](https://www.youtube.com/watch?v=TzNQs85fL1w) 7:40

### Q&A

1. 4번 페이지 최하단의 회색 공간은 무슨 공간인가요?
 4,5,6번 페이지에서 선택한 옵션이 하단 박스에 보이게 수정하려고 합니다.!
4번같은 경우는 하나만 선택하면 되는데, 5번 페이지는 선택지를 두개 선택하게 하려니
표시가 필요할 거 같아서 추가했습니다.
3. 5번 페이지는 9개의 키워드가 한 페이지를 이루고, 그걸 슬라이드를 통해 넘기는 형태인가요? (아니면 '>' 버튼일까요?)
9개를 한번에 넣으려고 하다가 4번페이지랑 6번 페이지보다 옵션이 너무 한번에 보여져서 통일성이 떨어지는 것 같아
네개씩 나눠서 페이지를 쪼개려고 해요. 5번 페이지 인터렉션은 4개 옵션->다른 4개옵션으로 넘어갈 때 4번 페이지처럼 이미지 각도가
비틀어지면 어떻냐는 의견이 있는데, 말로 설명드리려니 어려워서 짧게 설명드리는 회의를 해도 좋을 거 같습니다. 4 페이지 인터렉션 관련해서 저두
질문드릴 게 있어서요!
4. 6번 페이지의 이미지 뷰는 인스타 게시글의 이미지 뷰를 생각하면 되는 걸까요?
6번페이지의 경우에는 옆으로 넘어가는 버튼을 누르면 큰 이미지는 작아지고 다음 작은 이미지가 커지는 효과가 필요해요!
5. 모든 페이지를 안 거쳐도 '조향 시작하기' 버튼을 누르면 바로 조향 페이지로 넘어가나요? place, keyword, scent 페이지에서의 선택은 필수적인 게 아닌 건가요?
이 부분을 보완해서 하단 박스를 다 채운 경우에 맨 마지막 6번 페이지에서 조향 시작하기 버튼을 클릭할 수 있게 하려고 합니다!

**Comment by ENvironmentSet** [comment]
디자인 팀과 상의해야 할 부분:

- 각 페이지에서 선택 및 선택 취소는 어떻게?
- 하단에 모이는 선택지들은 관상용? 혹은 드래그 등의 동작으로 상호작용 가능?
- 버튼 디자인 통일(페이지 6)
- 페이지 4의 UX(선택 방식을 잘못 설계하면 불편할 것 같음.)

**Comment by kong33** [comment]
A - 우선 회의에 들은 내용 바탕으로 최대한 글로 설명해 보겠습니다. 이해 안가시는 부분 있으시면 저랑 줌이나 직접 만나서 회의하면 좋을 것 같아요!

1.4번 페이지 하단 회색 네모 네 개는 각 페이지에서 클릭해 고른 것들이 들어갈 박스입니다.
place에서는 고른 place의 사진이 , keyword에서도 고른 keyword의 사진이, scent에서도 고른 scent의 이미지가 들어갑니다. 각 페이지에서 선택은 해당 이미지를 포함한 div의 클릭으로 이루어지며 해제는 하단의 정사각형 박스를 두 번 클릭하면 할 수 있습니다. 이때 정사각형 박스를 한 번 클릭하면 해당 이미지의 투명도가 낮아지며 'x'표시를 띄웁니다. 한번 더 클릭 시 아예 취소가 되어 이미지가 사라지는 방식으로 구현하면 됩니다. 

이 때 클릭후 하단 정사각형 박스에 고른 이미지가 표시되는 방식은 이미지가 날라가서 하단 박스로 들어가도 되고 그냥 바로 하단 박스에 생겨도 될 것 같습니다. 아니면 드래그 해서 박스로 옮기면 박스에 자동으로 들어가게 하는 방법도 있을 것 같습니다! 디자인팀에서 이러한 사세한 모션까지 생각해두지 않으신 것 같아서 저희가 디자인에 조금씩 참여해서 개발하는 게 좋을 것 같아요. 하단 박스에 선택한 옵션이 보이게 하는 방법은 디자인팀과 상의하면 좋을 것 같습니다! 제 생각엔 투명도 높은 텍스트로 박스 안에 띄우는 것도 좋을 것 같네요! 

+ 4번 페이지에서 맨 앞에 위치한 해당 페이지를 클릭해 선택하게 되면, 밑의 frame2 에서 볼 수 있듯이  이미지 하단의 텍스트 박스의 투명도가 달라집니다. 이건 png 파일로 각각 투명도 높은 버전, 투명도 낮은 버전을 요청했으니 두 개 가져다 쓰시면 될 것 같습니다. 투명도가 바뀔 때 따로 애니메이션은 필요 없다고 하셨으나 혹시 개발 중 그라데이션이나 천천히 바뀌게 하는 등 애니메이션이 있는 게 낫다고 생각되시면 넣으면 될 것 같아요! 그렇다면 두 이미지 다 갖다 쓰실 필요 없이 css 로 구현해도 될 것 같습니다. 딱히 상관 없으신 것 같았습니다

더불어 페이지 4번의 ux는 제가 첨부한 영상의 ux와 거의 일치한다고 보시면 될 것 같습니다. 확인해보시고 재원님이 보시기에 저희 키오스크에서 불편할 것 같거나 고쳤으면 좋겠는 부분은 디자인팀과 같이 상의하면 좋을 것 같습니다! 

2. 5번페이지는 아직 변동이 많이 예상되는 페이지라 개발을 미루는 게 좋을 것 같습니다.회의 때 나온 의견으로는 저희가 전에 레퍼로 봤던 잉크 퍼지는 듯한 애니메이션이 필요할 수도 있을 것 같네요. 어쨌든 간에 저 레이아웃과는 크게 달라질 것으로 보입니다. 

3. 6번 페이지 역시 사운드 추가나 배경 색 변화 등 변동사항이 더 있을 것으로 예상됩니다만  해당 페이지를 선택하면 이미지가 커지고 나머지 옆 이미지들은 작아지는 모션은 그대로 갈 것 같습니다. 

논의 안 된 부분 => 버튼 디자인 통일. 이 부분은 같이 회의 때 말씀 드려보면 좋을 것 같습니다. 아직 3,4번 페이지를 제외한 페이지는 디자인 확정이 아니라 이번 회의를 통해 결정해도 좋을 것 같습니다. 아마도 배경 색 정도는 css로 변동을 줄 것 같아요..

**Comment by ENvironmentSet** [comment]
<img width="756" alt="image" src="https://github.com/s-center/kiosk/assets/28680594/68f4b0ba-bbef-4cae-bead-a1ab404572b4">

변경된 4, 5, 6번 화면 디자인입니다.

<img width="684" alt="image" src="https://github.com/s-center/kiosk/assets/28680594/201c1828-6a90-4b7c-99ba-12e0d942ea95">
<img width="614" alt="image" src="https://github.com/s-center/kiosk/assets/28680594/619a03a6-63f7-487c-b3a3-1f5acb9f35b3">

세부 디자인 요소들

**Comment by kong33** [comment]
제가 keyword 페이지 작업하고 있겠습니다! choosing 페이지 확인되면 다음 페이지 작업 부탁드려요!

**Comment by kong33** [comment]
4페이지 부터 존재하는 상단 두개 바와 로고, 하단 선택박스 각각 컴포넌트 만들고 합쳐서 레이아웃 컴포넌트 만들겠습니다:)
1. 상단 로고 
2. 상단 바 두개
3. 하단 정사각형 박스 

나머지 7페이지 , 13페이지~ , 3-1페이지~ 중에 편한거 골라서 만들어주세요! 
+ web GL 사용 해봤는데 커스텀이 어려워서 ㅠㅠ 혹시 코드 한 번 보시고 커스텀 가능하실 것 같으면 알려주세요!

**Comment by ENvironmentSet** [comment]
#14
